name: Build and Release

on:
  push:
    tags: # Trigger on tag pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          mkdir -p dist
          cp index.html index.js dist
          
      - name: Create zip
        run: |
          zip -r "${{ github.event.repository.name }}-${{ github.ref }}.zip" dist
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.repository.name }}-${{ github.ref }}.zip"
          path: "${{ github.event.repository.name }}-${{ github.ref }}.zip"

  release:
    runs-on: ubuntu-latest
    needs: build # This job is dependent on the build job
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: "Release notes for version ${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided secret

      - name: Upload zip to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          files: "${{ github.event.repository.name }}-${{ github.ref }}.zip" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided secret

